#!/usr/bin/env bash

###############################################################################
# RESISTOMETA
# Module 06 - Assembly Quality Assessment
#
# Purpose:
#   Evaluates metagenome assemblies generated by MEGAHIT using MetaQUAST.
#
# Usage:
#     bash 06_assembly_quality.sh SAMPLE_ID
###############################################################################

set -euo pipefail


###############################################################################
# DETERMINE PROJECT ROOT
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PROJECT_ROOT="$(dirname "$(dirname "$(dirname "${SCRIPT_DIR}")")")"


###############################################################################
# LOAD CONFIGURATION
###############################################################################

source "${PROJECT_ROOT}/config/config.sh"

source "${SCRIPT_DIR_BASH}/utils.sh"


###############################################################################
# MODULE DIRECTORIES
###############################################################################

MEGAHIT_DIR="${ASSEMBLY_DIR}/megahit"

METAQUAST_DIR="${ASSEMBLY_QC_DIR}/metaquast"


###############################################################################
# RUN ASSEMBLY QUALITY ASSESSMENT
###############################################################################

run_sample() {

    local SAMPLE_ID="$1"

    print_step_header \
        "Module 06 - Assembly Quality Assessment (${SAMPLE_ID})"


    ###########################################################################
    # INPUT FILE
    ###########################################################################

    local CONTIGS="${MEGAHIT_DIR}/${SAMPLE_ID}/final.contigs.fa"

    check_output "${CONTIGS}"


    ###########################################################################
    # OUTPUT DIRECTORY
    ###########################################################################

    create_directory "${METAQUAST_DIR}"


    ###########################################################################
    # SOFTWARE
    ###########################################################################

    activate_env "${MAIN_ENV}"

    check_tool metaquast.py


    ###########################################################################
    # OUTPUT DIRECTORY
    ###########################################################################

    local OUTPUT_DIR="${METAQUAST_DIR}/${SAMPLE_ID}"


    ###########################################################################
    # SKIP COMPLETED SAMPLE
    ###########################################################################

    if skip_step \
        "Assembly quality assessment (${SAMPLE_ID})" \
        "${OUTPUT_DIR}/report.html"
    then

        return 0

    fi


    ###########################################################################
    # METAQUAST
    ###########################################################################

    log_message "INFO" \
        "Running MetaQUAST..."

    run_command \
        metaquast.py \
        "${CONTIGS}" \
        -o "${OUTPUT_DIR}"


    ###########################################################################
    # VALIDATE OUTPUTS
    ###########################################################################

    check_output "${OUTPUT_DIR}/report.html"

    check_output "${OUTPUT_DIR}/report.txt"


    ###########################################################################
    # COMPLETION
    ###########################################################################

    log_message \
        "SUCCESS" \
        "Module 06 completed for sample ${SAMPLE_ID}."

}


###############################################################################
# MAIN
###############################################################################

if [[ $# -eq 0 ]]; then

    log_message \
        "ERROR" \
        "Usage: $0 SAMPLE_ID"

    exit 1

fi


run_sample "$1"