#!/usr/bin/env bash

###############################################################################
# RESISTOMETA PIPELINE CONFIGURATION
#
# Global configuration for the complete metagenomic AMR pipeline.
#
# Pipeline architecture:
#
#   Modules 01–07 : Bash-based bioinformatics processing
#   Module 08     : Launches downstream R analysis
#   R modules     : taxonomy, resistome and plasmid
#
# This file is the single configuration source for the pipeline.
###############################################################################


###############################################################################
# PROJECT INFORMATION
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"

PIPELINE_NAME="ResistoMeta"
PIPELINE_VERSION="1.0.0"
PIPELINE_AUTHOR="Hafeez T. Akinniyi"
PIPELINE_LICENSE="MIT"

DATE_FORMAT="+%Y-%m-%d %H:%M:%S"


###############################################################################
# COMPUTING RESOURCES
###############################################################################

THREADS=32
R_THREADS=8


###############################################################################
# CONDA
###############################################################################

CONDA_BASE="${HOME}/miniconda3"


###############################################################################
# CONDA ENVIRONMENTS
###############################################################################

# Main bioinformatics environment.
#
# Expected tools include:
#   FastQC
#   fastp
#   MultiQC
#   Bowtie2
#   Kraken2
#   Bracken
#   MEGAHIT
#   MetaQUAST
#   ABRicate
MAIN_ENV="main_env"

# RGI environment.
RGI_ENV="rgi_env"

# R analytical environment.
R_ENV="r_env"


###############################################################################
# PROJECT DIRECTORIES
###############################################################################

CONFIG_DIR="${PROJECT_ROOT}/config"

RAW_READS_DIR="${PROJECT_ROOT}/raw_data"

DATABASE_DIR="${PROJECT_ROOT}/databases"

DOCS_DIR="${PROJECT_ROOT}/docs"

LOG_DIR="${PROJECT_ROOT}/logs"


###############################################################################
# PIPELINE SCRIPTS
###############################################################################

SCRIPT_DIR_BASH="${PROJECT_ROOT}/scripts/bash"

SCRIPT_DIR_R="${PROJECT_ROOT}/scripts/R"

BASH_MODULE_DIR="${SCRIPT_DIR_BASH}/modules"

R_MODULE_DIR="${SCRIPT_DIR_R}/modules"


###############################################################################
# PIPELINE ENTRY POINTS
###############################################################################

RUN_PIPELINE_SCRIPT="${SCRIPT_DIR_BASH}/run_pipeline.sh"

VALIDATE_INSTALLATION_SCRIPT="${SCRIPT_DIR_BASH}/validate_installation.sh"

LAUNCH_R_ANALYSIS_SCRIPT="${BASH_MODULE_DIR}/08_launch_R_analysis.sh"

RUN_ANALYSIS_SCRIPT="${SCRIPT_DIR_R}/run_analysis.R"

TAXONOMY_ANALYSIS_SCRIPT="${R_MODULE_DIR}/taxonomy_analysis.R"

RESISTOME_ANALYSIS_SCRIPT="${R_MODULE_DIR}/resistome_analysis.R"

PLASMID_ANALYSIS_SCRIPT="${R_MODULE_DIR}/plasmid_analysis.R"


###############################################################################
# RESULTS ROOT
###############################################################################

RESULTS_DIR="${PROJECT_ROOT}/results"


###############################################################################
# UPSTREAM BIOINFORMATICS RESULTS
#
# Standardized outputs generated by Modules 01–07.
###############################################################################

QC_DIR="${RESULTS_DIR}/01_quality_control"

HOST_DEPLETION_DIR="${RESULTS_DIR}/02_host_depletion"

TAXONOMY_DIR="${RESULTS_DIR}/03_taxonomy"

READ_RESISTOME_DIR="${RESULTS_DIR}/04_read_based_resistome"

ASSEMBLY_DIR="${RESULTS_DIR}/05_assembly"

ASSEMBLY_QC_DIR="${RESULTS_DIR}/06_assembly_quality"

CONTIG_ANNOTATION_DIR="${RESULTS_DIR}/07_contig_annotation"

###############################################################################
# SEQUENCING_DEPTH_FILE
###############################################################################

# Sequencing depth for each sample.
#
# Required columns:
#   SampleID
#   total_sequences
#
# Used by downstream read-based resistome analysis for:
#   - sequencing-depth normalization
#   - RPKM calculation
#   - sample-universe definition

SEQUENCING_DEPTH_FILE="${READ_RESISTOME_DIR}/sequencing_depth.csv"


###############################################################################
# DOWNSTREAM ANALYSIS RESULTS
#
# Module 08 and the R workflow write outputs beneath:
#
#   results/08_downstream_analysis/
#       taxonomy/
#       resistome/
#       plasmids/
###############################################################################

ANALYSIS_DIR="${RESULTS_DIR}/08_downstream_analysis"

TAXONOMY_ANALYSIS_DIR="${ANALYSIS_DIR}/taxonomy"

RESISTOME_ANALYSIS_DIR="${ANALYSIS_DIR}/resistome"

PLASMID_ANALYSIS_DIR="${ANALYSIS_DIR}/plasmids"

FIGURE_DIR="${ANALYSIS_DIR}/figures"

OBJECT_DIR="${ANALYSIS_DIR}/objects"

###############################################################################
# DATABASES
###############################################################################

# Bowtie2 host reference index.
#
# Do not include .1/.2/etc. suffixes.

HOST_REFERENCE_INDEX="/path/to/bowtie2_host_index"

# Kraken2 database.
KRAKEN_DATABASE="/path/to/kraken2_database"


###############################################################################
# ABRICATE DATABASES
#
# Module 07 is the authoritative stage for ABRicate hit filtering.
#
# The identity and coverage thresholds below are applied by Module 07
# and the resulting filtered outputs are consumed by downstream R analysis.
###############################################################################

ABRICATE_CARD_DB="card"

ABRICATE_PLASMID_DB="plasmidfinder"


###############################################################################
# QUALITY CONTROL PARAMETERS
###############################################################################

MIN_READ_LENGTH=50

MIN_QUALITY=20


###############################################################################
# KRAKEN2 / BRACKEN PARAMETERS
###############################################################################

# Effective read length used by Bracken.
BRACKEN_READ_LENGTH=150


###############################################################################
# RGI READ-BASED RESISTOME PARAMETERS
#
# These parameters apply to RGI read-based ARG detection.
#
# RGI filtering is performed in resistome_analysis.R.
###############################################################################

# Minimum number of reads mapped to an ARG for inclusion.
RGI_MIN_MAPPED_READS=5

# Minimum average percentage coverage of the reference ARG.
RGI_MIN_COVERAGE=80


###############################################################################
# ABRICATE CONTIG-BASED AMR PARAMETERS
#
# These are the authoritative identity and coverage thresholds for
# ABRicate CARD and PlasmidFinder analyses performed in Module 07.
#
# Downstream R modules consume the resulting filtered outputs and do not
# independently redefine these primary hit-detection thresholds.
###############################################################################

ABRICATE_MIN_IDENTITY=80

ABRICATE_MIN_COVERAGE=80


###############################################################################
# TAXONOMIC ANALYSIS PARAMETERS
###############################################################################

TOP_GENERA=15

TOP_PHYLA=10

TOP_SPECIES=15


###############################################################################
# TAXONOMIC LEVELS
###############################################################################

TAXONOMIC_LEVELS="phylum genus species"


###############################################################################
# TAXONOMY ABUNDANCE
###############################################################################

# Bracken provides:
#
#   new_est_reads
#   fraction_total_reads
#
# The downstream taxonomy analysis uses estimated-read counts and
# generates relative-abundance matrices.

TAXONOMY_ABUNDANCE_SCALE="relative"


###############################################################################
# RGI RESISTOME ABUNDANCE
###############################################################################

# Primary abundance metric for read-based ARG analysis.
#
# RPKM accounts for:
#   1. sequencing depth
#   2. ARG reference length
#
# Raw mapped reads and ARG richness remain separate measures.

RESISTOME_ABUNDANCE_METRIC="RPKM"


###############################################################################
# RESISTOME ANALYSIS
###############################################################################

CALCULATE_ARG_RICHNESS=true

CALCULATE_ARG_PREVALENCE=true

CALCULATE_ARG_CLASS_ABUNDANCE=true

CALCULATE_ARG_CLASS_RICHNESS=true


###############################################################################
# CONTIG-BASED AMR ANALYSIS
###############################################################################

CALCULATE_ABRICATE_RICHNESS=true

CALCULATE_ABRICATE_PREVALENCE=true


###############################################################################
# PLASMID / ARG LOCALIZATION ANALYSIS
###############################################################################

CALCULATE_PLASMID_RICHNESS=true

CALCULATE_PLASMID_PREVALENCE=true

CALCULATE_SAMPLE_CO_OCCURRENCE=true

CALCULATE_CONTIG_COLOCALIZATION=true


###############################################################################
# FIGURE GENERATION
###############################################################################

GENERATE_FIGURES=true

SAVE_PNG=true

SAVE_PDF=true

FIGURE_DPI=300

FIGURE_WIDTH=10

FIGURE_HEIGHT=7


###############################################################################
# PIPELINE VALIDATION
###############################################################################

CHECK_INPUTS=true

CHECK_OUTPUTS=true

STOP_ON_ERROR=true


###############################################################################
# PIPELINE MODE
###############################################################################

# full
#     Execute Modules 01–08.
#
# bioinformatics
#     Execute Modules 01–07.
#
# analysis
#     Execute Module 08 / downstream R analysis only.

PIPELINE_MODE="full"


###############################################################################
# BIOINFORMATICS MODULES
###############################################################################

RUN_QC=true

RUN_HOST_DEPLETION=true

RUN_TAXONOMY=true

RUN_READ_RESISTOME=true

RUN_ASSEMBLY=true

# Module 06 can substantially increase runtime and is disabled by default.
# Set to true when assembly-quality assessment is required.
RUN_ASSEMBLY_QC=false

RUN_CONTIG_ANNOTATION=true


###############################################################################
# DOWNSTREAM R ANALYSIS
###############################################################################

RUN_R_ANALYSIS=true


###############################################################################
# INDIVIDUAL R ANALYSIS MODULES
###############################################################################

RUN_TAXONOMY_ANALYSIS=true

RUN_RESISTOME_ANALYSIS=true

RUN_PLASMID_ANALYSIS=true
