#!/usr/bin/env Rscript

###############################################################################
# RESISTOMETA
# Module: Taxonomy Analysis
#
# File:
#   taxonomy_analysis.R
#
# Purpose:
#   Perform generic downstream taxonomic abundance processing from
#   Bracken abundance estimates generated by the upstream taxonomy module.
#
# Scope:
#
#   1. Import Bracken abundance estimates
#   2. Validate Bracken sample/file consistency
#   3. Process configured taxonomic levels
#   4. Generate estimated-read abundance matrices
#   5. Generate relative-abundance matrices
#   6. Calculate taxon-level summaries
#   7. Calculate taxon prevalence
#   8. Identify dominant/top taxa
#   9. Generate sample-level abundance summaries
#  10. Save structured taxonomy analysis objects
#
# IMPORTANT:
#
#   This module is intentionally independent of study-specific metadata.
#
#   The sample universe is derived directly from the valid Bracken files
#   detected in TAXONOMY_DIR.
#
#   Therefore:
#
#       Prevalence denominator =
#       number of samples with valid Bracken results at that taxonomic level
#
#   config.sh remains the SINGLE SOURCE OF TRUTH.
#
#   Analytical configuration is received through environment variables
#   exported by Module 08.
#
#   This module does NOT:
#
#       - use study-specific metadata
#       - perform differential abundance analysis
#       - perform statistical hypothesis testing
#       - redefine analytical thresholds
#       - redefine pipeline switches
#
# Taxonomic levels are controlled by:
#
#       METAGENOMIC_AMR_TAXONOMIC_LEVELS
#
# Supported levels:
#
#       phylum
#       genus
#       species
#
# Abundance:
#
#   Bracken new_est_reads are retained as the count/estimated-read matrix.
#
#   Relative abundance is calculated within each sample from the
#   estimated-read matrix.
#
###############################################################################


###############################################################################
# 1. LOAD REQUIRED PACKAGES
###############################################################################

required_packages <- c(
    "dplyr",
    "tidyr",
    "readr"
)


missing_packages <- required_packages[
    !vapply(
        required_packages,
        requireNamespace,
        quietly = TRUE,
        FUN.VALUE = logical(1)
    )
]


if (length(missing_packages) > 0) {

    stop(
        paste0(
            "The following R packages are required but not installed:\n",
            paste(
                missing_packages,
                collapse = ", "
            )
        )
    )

}


suppressPackageStartupMessages({

    library(dplyr)
    library(tidyr)
    library(readr)

})


###############################################################################
# 2. ENVIRONMENT HELPERS
###############################################################################

get_env <- function(
    name,
    required = TRUE,
    default = NULL
) {

    value <- Sys.getenv(
        name,
        unset = ""
    )


    if (identical(value, "")) {

        if (required) {

            stop(
                paste0(
                    "Required environment variable is not set: ",
                    name
                )
            )

        }

        return(default)

    }


    value

}


###############################################################################
# Boolean configuration parser
###############################################################################

as_bool <- function(x) {

    if (
        length(x) == 0 ||
        is.na(x) ||
        identical(trimws(x), "")
    ) {

        stop(
            "A Boolean configuration value is missing."
        )

    }


    value <- tolower(
        trimws(x)
    )


    valid_values <- c(
        "true",
        "false",
        "t",
        "f",
        "1",
        "0",
        "yes",
        "no",
        "y",
        "n"
    )


    if (!value %in% valid_values) {

        stop(
            sprintf(
                "Invalid Boolean configuration value: '%s'",
                x
            )
        )

    }


    value %in% c(
        "true",
        "t",
        "1",
        "yes",
        "y"
    )

}


###############################################################################
# Logging helper
###############################################################################

log_taxonomy <- function(...) {

    message(
        paste0(
            "[TAXONOMY] ",
            paste0(..., collapse = "")
        )
    )

}


###############################################################################
# 3. READ ENVIRONMENT CONFIGURATION
###############################################################################

log_taxonomy(
    "Reading taxonomy analysis configuration..."
)


###############################################################################
# Upstream taxonomy results
###############################################################################

TAXONOMY_DIR <- get_env(
    "METAGENOMIC_AMR_TAXONOMY_DIR"
)


###############################################################################
# Taxonomy analysis output directory
###############################################################################

TAXONOMY_ANALYSIS_DIR <- get_env(
    "METAGENOMIC_AMR_TAXONOMY_ANALYSIS_DIR"
)


###############################################################################
# Shared R analysis object directory
###############################################################################

OBJECT_DIR <- get_env(
    "METAGENOMIC_AMR_ANALYSIS_OBJECT_DIR"
)


###############################################################################
# Configured taxonomic levels
###############################################################################

TAXONOMIC_LEVELS_RAW <- get_env(
    "METAGENOMIC_AMR_TAXONOMIC_LEVELS"
)


###############################################################################
# Top-taxon parameters
###############################################################################

TOP_GENERA <- as.integer(
    get_env(
        "METAGENOMIC_AMR_TOP_GENERA"
    )
)


TOP_PHYLA <- as.integer(
    get_env(
        "METAGENOMIC_AMR_TOP_PHYLA"
    )
)


TOP_SPECIES <- as.integer(
    get_env(
        "METAGENOMIC_AMR_TOP_SPECIES"
    )
)


###############################################################################
# Taxonomy abundance scale
###############################################################################

TAXONOMY_ABUNDANCE_SCALE <- get_env(
    "METAGENOMIC_AMR_TAXONOMY_ABUNDANCE_SCALE"
)


###############################################################################
# 4. VALIDATE CONFIGURATION
###############################################################################

###############################################################################
# Taxonomic levels
###############################################################################

TAXONOMIC_LEVELS <- unique(
    tolower(
        trimws(
            unlist(
                strsplit(
                    TAXONOMIC_LEVELS_RAW,
                    "[,[:space:]]+"
                )
            )
        )
    )
)


TAXONOMIC_LEVELS <- TAXONOMIC_LEVELS[
    TAXONOMIC_LEVELS != ""
]


SUPPORTED_TAXONOMIC_LEVELS <- c(
    "phylum",
    "genus",
    "species"
)


unsupported_levels <- setdiff(
    TAXONOMIC_LEVELS,
    SUPPORTED_TAXONOMIC_LEVELS
)


if (length(unsupported_levels) > 0) {

    stop(
        paste0(
            "Unsupported taxonomic level(s) configured in ",
            "METAGENOMIC_AMR_TAXONOMIC_LEVELS:\n",
            paste(
                unsupported_levels,
                collapse = ", "
            ),
            "\nSupported levels are: ",
            paste(
                SUPPORTED_TAXONOMIC_LEVELS,
                collapse = ", "
            )
        )
    )

}


if (length(TAXONOMIC_LEVELS) == 0) {

    stop(
        "No taxonomic levels were configured in METAGENOMIC_AMR_TAXONOMIC_LEVELS."
    )

}


###############################################################################
# Top-taxon parameters
###############################################################################

if (
    is.na(TOP_GENERA) ||
    TOP_GENERA < 1
) {

    stop(
        "METAGENOMIC_AMR_TOP_GENERA must be a positive integer."
    )

}


if (
    is.na(TOP_PHYLA) ||
    TOP_PHYLA < 1
) {

    stop(
        "METAGENOMIC_AMR_TOP_PHYLA must be a positive integer."
    )

}


if (
    is.na(TOP_SPECIES) ||
    TOP_SPECIES < 1
) {

    stop(
        "METAGENOMIC_AMR_TOP_SPECIES must be a positive integer."
    )

}


###############################################################################
# Abundance scale
###############################################################################

TAXONOMY_ABUNDANCE_SCALE <- tolower(
    trimws(
        TAXONOMY_ABUNDANCE_SCALE
    )
)


if (
    !TAXONOMY_ABUNDANCE_SCALE %in%
    c(
        "relative",
        "count",
        "both"
    )
) {

    stop(
        paste0(
            "Unsupported taxonomy abundance scale: ",
            TAXONOMY_ABUNDANCE_SCALE,
            "\nSupported values are: relative, count, both."
        )
    )

}


###############################################################################
# 5. CREATE OUTPUT DIRECTORIES
###############################################################################

dir.create(
    TAXONOMY_ANALYSIS_DIR,
    recursive = TRUE,
    showWarnings = FALSE
)


dir.create(
    OBJECT_DIR,
    recursive = TRUE,
    showWarnings = FALSE
)


###############################################################################
# 6. LOG ACTIVE CONFIGURATION
###############################################################################

message("============================================================")
message("TAXONOMY ABUNDANCE ANALYSIS")
message("============================================================")


log_taxonomy(
    "Taxonomy results directory: ",
    TAXONOMY_DIR
)


log_taxonomy(
    "Taxonomy analysis directory: ",
    TAXONOMY_ANALYSIS_DIR
)


log_taxonomy(
    "Configured taxonomic levels: ",
    paste(
        TAXONOMIC_LEVELS,
        collapse = ", "
    )
)


log_taxonomy(
    "Top genera: ",
    TOP_GENERA
)


log_taxonomy(
    "Top phyla: ",
    TOP_PHYLA
)


log_taxonomy(
    "Top species: ",
    TOP_SPECIES
)


log_taxonomy(
    "Taxonomy abundance scale: ",
    TAXONOMY_ABUNDANCE_SCALE
)


log_taxonomy(
    "Sample universe: derived directly from valid Bracken files"
)


###############################################################################
# 7. VALIDATE INPUT DIRECTORY
###############################################################################

log_taxonomy(
    "Validating taxonomy analysis inputs..."
)


if (!dir.exists(TAXONOMY_DIR)) {

    stop(
        paste0(
            "Taxonomy results directory not found:\n",
            TAXONOMY_DIR
        )
    )

}


###############################################################################
# 8. DISCOVER BRACKEN FILES
###############################################################################

log_taxonomy(
    "Searching for Bracken abundance files..."
)


all_bracken_files <- list.files(
    TAXONOMY_DIR,
    pattern = "\\.bracken$",
    recursive = TRUE,
    full.names = TRUE
)


if (length(all_bracken_files) == 0) {

    stop(
        paste0(
            "No Bracken output files were found in:\n",
            TAXONOMY_DIR
        )
    )

}


###############################################################################
# Genus files
#
# Expected pipeline naming convention:
#
#     SAMPLE_ID_genus.bracken
#
###############################################################################

genus_files <- all_bracken_files[
    grepl(
        "_genus\\.bracken$",
        basename(all_bracken_files),
        ignore.case = TRUE
    )
]


###############################################################################
# Phylum files
#
# Expected pipeline naming convention:
#
#     SAMPLE_ID_phylum.bracken
#
###############################################################################

phylum_files <- all_bracken_files[
    grepl(
        "_phylum\\.bracken$",
        basename(all_bracken_files),
        ignore.case = TRUE
    )
]


###############################################################################
# Species files
#
# Expected pipeline naming convention:
#
#     SAMPLE_ID_species.bracken
#
###############################################################################

species_files <- all_bracken_files[
    grepl(
        "_species\\.bracken$",
        basename(all_bracken_files),
        ignore.case = TRUE
    )
]


log_taxonomy(
    "Total Bracken files detected: ",
    length(all_bracken_files)
)


log_taxonomy(
    "Genus files detected: ",
    length(genus_files)
)


log_taxonomy(
    "Phylum files detected: ",
    length(phylum_files)
)


log_taxonomy(
    "Species files detected: ",
    length(species_files)
)

###############################################################################
# Validate expected Bracken file counts
###############################################################################

if (
    "phylum" %in% TAXONOMIC_LEVELS &&
    length(phylum_files) == 0
) {

    stop(
        paste0(
            "Taxonomic level 'phylum' was requested but no corresponding ",
            "Bracken files were detected in:\n",
            TAXONOMY_DIR
        )
    )

}


if (
    "genus" %in% TAXONOMIC_LEVELS &&
    length(genus_files) == 0
) {

    stop(
        paste0(
            "Taxonomic level 'genus' was requested but no corresponding ",
            "Bracken files were detected in:\n",
            TAXONOMY_DIR
        )
    )

}


if (
    "species" %in% TAXONOMIC_LEVELS &&
    length(species_files) == 0
) {

    stop(
        paste0(
            "Taxonomic level 'species' was requested but no corresponding ",
            "Bracken files were detected in:\n",
            TAXONOMY_DIR
        )
    )

}


###############################################################################
# 9. MAP TAXONOMIC LEVELS TO FILES AND PARAMETERS
###############################################################################

taxonomy_file_map <- list(

    phylum =
        phylum_files,

    genus =
        genus_files,

    species =
        species_files

)


taxonomy_code_map <- c(

    phylum =
        "P",

    genus =
        "G",

    species =
        "S"

)


taxonomy_top_n_map <- c(

    phylum =
        TOP_PHYLA,

    genus =
        TOP_GENERA,

    species =
        TOP_SPECIES

)


###############################################################################
# 10. EXTRACT SAMPLE ID FROM BRACKEN FILENAME
###############################################################################

extract_sample_id <- function(
    filename,
    level
) {

    basename_file <- basename(
        filename
    )


    patterns <- switch(

        level,

        genus = c(
            "_genus\\.bracken$"
        ),

        phylum = c(
            "_phylum\\.bracken$"
        ),

        species = c(
            "_species\\.bracken$"
        ),

        character(0)

    )


    sample_id <- basename_file


    for (pattern in patterns) {

        sample_id <- sub(
            pattern,
            "",
            sample_id,
            ignore.case = TRUE
        )

    }


    if (
        is.na(sample_id) ||
        sample_id == ""
    ) {

        stop(
            paste0(
                "Unable to extract SampleID from Bracken filename:\n",
                basename_file
            )
        )

    }


    sample_id

}


###############################################################################
# 11. READ BRACKEN FILES
###############################################################################

read_bracken_files <- function(
    files,
    taxonomy_level,
    expected_taxonomy_code
) {

    if (length(files) == 0) {

        return(NULL)

    }


    ###########################################################################
    # Extract SampleIDs
    ###########################################################################

    sample_ids <- vapply(
        files,
        extract_sample_id,
        FUN.VALUE = character(1),
        level = taxonomy_level
    )


    ###########################################################################
    # Check duplicate SampleIDs
    ###########################################################################

    duplicated_samples <- unique(
        sample_ids[
            duplicated(sample_ids)
        ]
    )


    if (length(duplicated_samples) > 0) {

        stop(
            paste0(
                "Multiple Bracken files detected for the same ",
                taxonomy_level,
                "-level SampleID:\n",
                paste(
                    duplicated_samples,
                    collapse = ", "
                )
            )
        )

    }


    ###########################################################################
    # Read files
    ###########################################################################

    result <- lapply(

        seq_along(files),

        function(i) {

            file <- files[i]

            sample_id <- sample_ids[i]


            log_taxonomy(
                "Reading ",
                taxonomy_level,
                " Bracken file: ",
                basename(file)
            )


            df <- read_tsv(
                file,
                show_col_types = FALSE,
                progress = FALSE
            )


            required_columns <- c(
                "name",
                "taxonomy_id",
                "taxonomy_lvl",
                "new_est_reads",
                "fraction_total_reads"
            )


            missing_columns <- setdiff(
                required_columns,
                colnames(df)
            )


            if (length(missing_columns) > 0) {

                stop(
                    paste0(
                        "Bracken file is missing required columns:\n",
                        basename(file),
                        "\nMissing: ",
                        paste(
                            missing_columns,
                            collapse = ", "
                        )
                    )
                )

            }


            ###################################################################
            # Standardize data types
            ###################################################################

            df <- df %>%

                mutate(

                    taxonomy_lvl =
                        as.character(
                            taxonomy_lvl
                        ),

                    new_est_reads =
                        suppressWarnings(
                            as.numeric(
                                new_est_reads
                            )
                        ),

                    fraction_total_reads =
                        suppressWarnings(
                            as.numeric(
                                fraction_total_reads
                            )
                        ),

                    SampleID =
                        sample_id,

                    Taxonomic_Level =
                        taxonomy_level

                )


            ###################################################################
            # Validate abundance values
            ###################################################################

            if (
                any(
                    !is.finite(df$new_est_reads) |
                    df$new_est_reads < 0
                )
            ) {

                stop(
                    paste0(
                        "Invalid new_est_reads values detected in:\n",
                        file
                    )
                )

            }


            if (
                any(
                    !is.finite(df$fraction_total_reads) |
                    df$fraction_total_reads < 0
                )
            ) {

                stop(
                    paste0(
                        "Invalid fraction_total_reads values detected in:\n",
                        file
                    )
                )

            }


            ###################################################################
            # Retain expected taxonomy level
            ###################################################################

            df <- df %>%

                filter(
                    taxonomy_lvl ==
                        expected_taxonomy_code
                )


            ###################################################################
            # Remove invalid taxon names
            ###################################################################

            df <- df %>%

                filter(
                    !is.na(name),
                    trimws(name) != ""
                )


            df

        }

    )


    bind_rows(
        result
    )

}


###############################################################################
# 12. VALIDATE TAXONOMIC SAMPLE SET
###############################################################################

validate_taxonomy_samples <- function(
    data,
    level
) {

    if (
        is.null(data) ||
        nrow(data) == 0
    ) {

        return(
            list(

                level =
                    level,

                analyzed =
                    character(0),

                n_samples =
                    0

            )
        )

    }


    sample_ids <- sort(
        unique(
            data$SampleID
        )
    )


    if (length(sample_ids) == 0) {

        warning(
            paste0(
                "No valid samples detected for ",
                level,
                "-level taxonomy."
            )
        )

    }


    list(

        level =
            level,

        analyzed =
            sample_ids,

        n_samples =
            length(sample_ids)

    )

}


###############################################################################
# 13. CREATE ABUNDANCE MATRIX
###############################################################################

create_abundance_matrix <- function(
    data,
    sample_ids
) {

    if (
        is.null(data) ||
        nrow(data) == 0 ||
        length(sample_ids) == 0
    ) {

        return(
            matrix(
                numeric(0),
                nrow = 0,
                ncol = 0
            )
        )

    }


    matrix_df <- data %>%

        filter(
            SampleID %in% sample_ids
        ) %>%

        select(
            SampleID,
            name,
            new_est_reads
        ) %>%

        group_by(
            SampleID,
            name
        ) %>%

        summarise(

            abundance =
                sum(
                    new_est_reads,
                    na.rm = TRUE
                ),

            .groups = "drop"

        ) %>%

        pivot_wider(

            names_from =
                name,

            values_from =
                abundance,

            values_fill =
                0

        )


    matrix_df <- as.data.frame(
        matrix_df,
        check.names = FALSE
    )


    rownames(matrix_df) <-
        matrix_df$SampleID


    matrix_df$SampleID <- NULL


    as.matrix(
        matrix_df
    )

}


###############################################################################
# 14. CONVERT ESTIMATED READS TO RELATIVE ABUNDANCE
###############################################################################

to_relative_abundance <- function(
    count_matrix
) {

    if (
        is.null(count_matrix) ||
        length(count_matrix) == 0 ||
        nrow(count_matrix) == 0 ||
        ncol(count_matrix) == 0
    ) {

        return(
            count_matrix
        )

    }


    sample_totals <- rowSums(
        count_matrix,
        na.rm = TRUE
    )


    invalid_samples <- rownames(
        count_matrix
    )[
        !is.finite(sample_totals) |
        sample_totals <= 0
    ]


    if (length(invalid_samples) > 0) {

        stop(
            paste0(
                "Samples with zero or invalid total taxonomic abundance:\n",
                paste(
                    invalid_samples,
                    collapse = ", "
                )
            )
        )

    }


    sweep(
        count_matrix,
        1,
        sample_totals,
        "/"
    )

}


###############################################################################
# 15. BASIC TAXON SUMMARY
###############################################################################

summarize_taxa <- function(
    count_matrix,
    relative_matrix
) {

    if (
        is.null(count_matrix) ||
        nrow(count_matrix) == 0 ||
        ncol(count_matrix) == 0
    ) {

        return(
            data.frame()
        )

    }


    mean_relative_abundance <- colMeans(
        relative_matrix,
        na.rm = TRUE
    )


    prevalence <- colSums(
        count_matrix > 0,
        na.rm = TRUE
    )


    total_abundance <- colSums(
        count_matrix,
        na.rm = TRUE
    )


    n_samples <- nrow(
        count_matrix
    )


    summary <- data.frame(

        Taxon =
            colnames(
                count_matrix
            ),

        Total_Estimated_Reads =
            as.numeric(
                total_abundance
            ),

        Mean_Relative_Abundance =
            as.numeric(
                mean_relative_abundance
            ),

        Prevalence_Count =
            as.numeric(
                prevalence
            ),

        Prevalence_Denominator =
            n_samples,

        Prevalence_Percent =
            as.numeric(
                prevalence /
                n_samples *
                100
            ),

        stringsAsFactors = FALSE

    )


    summary %>%

        arrange(
            desc(
                Mean_Relative_Abundance
            )
        )

}


###############################################################################
# 16. SAMPLE-LEVEL ABUNDANCE SUMMARY
###############################################################################

summarize_samples <- function(
    count_matrix,
    relative_matrix
) {

    if (
        is.null(count_matrix) ||
        nrow(count_matrix) == 0
    ) {

        return(
            data.frame()
        )

    }


    data.frame(

        SampleID =
            rownames(
                count_matrix
            ),

        Total_Estimated_Reads =
            rowSums(
                count_matrix,
                na.rm = TRUE
            ),

        Number_of_Taxa_Detected =
            rowSums(
                count_matrix > 0,
                na.rm = TRUE
            ),

        Mean_Taxon_Relative_Abundance =
            rowMeans(
                relative_matrix,
                na.rm = TRUE
            ),

        stringsAsFactors = FALSE

    )

}


###############################################################################
# 17. IDENTIFY TOP TAXA
###############################################################################

identify_top_taxa <- function(
    relative_matrix,
    n_taxa
) {

    if (
        is.null(relative_matrix) ||
        nrow(relative_matrix) == 0 ||
        ncol(relative_matrix) == 0
    ) {

        return(
            character(0)
        )

    }


    mean_abundance <- colMeans(
        relative_matrix,
        na.rm = TRUE
    )


    ordered_taxa <- names(
        sort(
            mean_abundance,
            decreasing = TRUE
        )
    )


    ordered_taxa[
        seq_len(
            min(
                n_taxa,
                length(ordered_taxa)
            )
        )
    ]

}


###############################################################################
# 18. WRITE MATRIX
###############################################################################

write_matrix <- function(
    matrix_object,
    file
) {

    if (
        is.null(matrix_object) ||
        length(matrix_object) == 0
    ) {

        return(
            invisible(NULL)
        )

    }


    df <- as.data.frame(
        matrix_object,
        check.names = FALSE
    )


    df <- data.frame(

        SampleID =
            rownames(df),

        df,

        check.names = FALSE

    )


    write_tsv(
        df,
        file
    )

}


###############################################################################
# 19. PROCESS TAXONOMIC LEVEL
###############################################################################

process_taxonomic_level <- function(
    files,
    level,
    expected_code,
    top_n
) {

    if (length(files) == 0) {

        stop(
            paste0(
                "Taxonomic level '",
                level,
                "' was requested but no corresponding Bracken ",
                "files were detected in:\n",
                TAXONOMY_DIR
            )
        )

    }


    log_taxonomy(
        "Processing ",
        level,
        "-level Bracken data..."
    )


    ###########################################################################
    # Read Bracken data
    ###########################################################################

    bracken_data <- read_bracken_files(

        files =
            files,

        taxonomy_level =
            level,

        expected_taxonomy_code =
            expected_code

    )


    if (
        is.null(bracken_data) ||
        nrow(bracken_data) == 0
    ) {

        stop(
            paste0(
                "No valid ",
                level,
                "-level Bracken records remained after validation."
            )
        )

    }


    ###########################################################################
    # Determine sample universe
    ###########################################################################

    sample_qc <- validate_taxonomy_samples(

        data =
            bracken_data,

        level =
            level

    )


    analyzed_samples <-
        sample_qc$analyzed


    if (length(analyzed_samples) == 0) {

        stop(
            paste0(
                "No valid samples were identified for ",
                level,
                "-level taxonomy."
            )
        )

    }


    ###########################################################################
    # Create estimated-read abundance matrix
    ###########################################################################

    counts <- create_abundance_matrix(

        data =
            bracken_data,

        sample_ids =
            analyzed_samples

    )


    if (
        nrow(counts) == 0 ||
        ncol(counts) == 0
    ) {

        stop(
            paste0(
                "No usable ",
                level,
                "-level abundance matrix could be created."
            )
        )

    }


    ###########################################################################
    # Relative abundance
    ###########################################################################

    relative_abundance <- to_relative_abundance(
        counts
    )


    ###########################################################################
    # Taxon summary
    ###########################################################################

    summary <- summarize_taxa(

        count_matrix =
            counts,

        relative_matrix =
            relative_abundance

    )


    ###########################################################################
    # Sample summary
    ###########################################################################

    sample_summary <- summarize_samples(

        count_matrix =
            counts,

        relative_matrix =
            relative_abundance

    )


    ###########################################################################
    # Top taxa
    ###########################################################################

    top_taxa <- identify_top_taxa(

        relative_matrix =
            relative_abundance,

        n_taxa =
            top_n

    )


    ###########################################################################
    # Write estimated-read matrix
    ###########################################################################

    if (
        TAXONOMY_ABUNDANCE_SCALE %in%
        c(
            "count",
            "both"
        )
    ) {

        write_matrix(

            counts,

            file.path(
                TAXONOMY_ANALYSIS_DIR,
                paste0(
                    level,
                    "_estimated_reads.tsv"
                )
            )

        )

    }


    ###########################################################################
    # Write relative-abundance matrix
    ###########################################################################

    if (
        TAXONOMY_ABUNDANCE_SCALE %in%
        c(
            "relative",
            "both"
        )
    ) {

        write_matrix(

            relative_abundance,

            file.path(
                TAXONOMY_ANALYSIS_DIR,
                paste0(
                    level,
                    "_relative_abundance.tsv"
                )
            )

        )

    }


    ###########################################################################
    # Always write taxon summary
    ###########################################################################

    write_tsv(

        summary,

        file.path(
            TAXONOMY_ANALYSIS_DIR,
            paste0(
                level,
                "_summary.tsv"
            )
        )

    )


    ###########################################################################
    # Always write sample summary
    ###########################################################################

    write_tsv(

        sample_summary,

        file.path(
            TAXONOMY_ANALYSIS_DIR,
            paste0(
                level,
                "_sample_summary.tsv"
            )
        )

    )


    ###########################################################################
    # Write top taxa
    ###########################################################################

    write_tsv(

        data.frame(
            Taxon =
                top_taxa
        ),

        file.path(
            TAXONOMY_ANALYSIS_DIR,
            paste0(
                "top_",
                level,
                ".tsv"
            )
        )

    )


    ###########################################################################
    # Log results
    ###########################################################################

    log_taxonomy(
        level,
        "-level samples analyzed: ",
        nrow(counts)
    )


    log_taxonomy(
        level,
        "-level taxa detected: ",
        ncol(counts)
    )


    log_taxonomy(
        level,
        "-level top taxa identified: ",
        length(top_taxa)
    )


    log_taxonomy(
        level,
        "-level prevalence denominator: ",
        nrow(counts),
        " samples"
    )


    ###########################################################################
    # Return structured object
    ###########################################################################

    list(

        level =
            level,

        sample_qc =
            sample_qc,

        raw =
            bracken_data,

        counts =
            counts,

        relative_abundance =
            relative_abundance,

        summary =
            summary,

        sample_summary =
            sample_summary,

        top_taxa =
            top_taxa

    )

}


###############################################################################
# 20. PROCESS CONFIGURED TAXONOMIC LEVELS
###############################################################################

taxonomy_results_by_level <- list()


for (level in TAXONOMIC_LEVELS) {

    log_taxonomy(
        "------------------------------------------------------------"
    )


    taxonomy_results_by_level[[level]] <-
        process_taxonomic_level(

            files =
                taxonomy_file_map[[level]],

            level =
                level,

            expected_code =
                taxonomy_code_map[[level]],

            top_n =
                taxonomy_top_n_map[[level]]

        )

}


###############################################################################
# 21. BUILD SAMPLE QC OBJECT
###############################################################################

sample_qc <- lapply(

    taxonomy_results_by_level,

    function(result) {

        result$sample_qc

    }

)


###############################################################################
# 22. SAVE SAMPLE QC INFORMATION
###############################################################################

saveRDS(

    sample_qc,

    file.path(
        OBJECT_DIR,
        "taxonomy_sample_qc.rds"
    )

)


###############################################################################
# 23. SAVE STRUCTURED TAXONOMY ANALYSIS OBJECT
###############################################################################

taxonomy_results <- list(

    configuration =
        list(

            taxonomic_levels =
                TAXONOMIC_LEVELS,

            top_genera =
                TOP_GENERA,

            top_phyla =
                TOP_PHYLA,

            top_species =
                TOP_SPECIES,

            abundance_scale =
                TAXONOMY_ABUNDANCE_SCALE

        ),

    sample_qc =
        sample_qc,

    results =
        taxonomy_results_by_level

)


saveRDS(

    taxonomy_results,

    file.path(
        OBJECT_DIR,
        "taxonomy_analysis.rds"
    )

)


###############################################################################
# 24. WRITE TAXONOMY ANALYSIS SUMMARY
###############################################################################

taxonomy_summary_file <- file.path(

    TAXONOMY_ANALYSIS_DIR,

    "taxonomy_analysis_summary.txt"

)


sink(
    taxonomy_summary_file
)


cat(
    "METAGENOMIC AMR PIPELINE\n"
)

cat(
    "Taxonomy Analysis Summary\n"
)

cat(
    "=========================\n\n"
)


cat(
    "Taxonomic levels analyzed: ",
    paste(
        TAXONOMIC_LEVELS,
        collapse = ", "
    ),
    "\n\n",
    sep = ""
)


cat(
    "Abundance scale: ",
    TAXONOMY_ABUNDANCE_SCALE,
    "\n\n",
    sep = ""
)


for (level in TAXONOMIC_LEVELS) {

    result <- taxonomy_results_by_level[[level]]


    cat(
        toupper(level),
        "\n",
        sep = ""
    )

    cat(
        strrep(
            "-",
            nchar(level)
        ),
        "\n",
        sep = ""
    )


    cat(
        "Samples analyzed: ",
        result$sample_qc$n_samples,
        "\n",
        sep = ""
    )


    cat(
        "Taxa detected: ",
        ncol(result$counts),
        "\n",
        sep = ""
    )


    cat(
        "Prevalence denominator: ",
        result$sample_qc$n_samples,
        " samples\n",
        sep = ""
    )


    cat(
        "Top taxa reported: ",
        length(result$top_taxa),
        "\n\n",
        sep = ""
    )

}


cat(
    "Sample universe:\n"
)

cat(
    "Derived directly from valid Bracken files at each taxonomic level.\n\n"
)


cat(
    "No study-specific metadata were used.\n"
)


sink()


###############################################################################
# 25. COMPLETION SUMMARY
###############################################################################

message("")
message("============================================================")
message("TAXONOMY ABUNDANCE ANALYSIS COMPLETED")
message("============================================================")


for (level in TAXONOMIC_LEVELS) {

    result <- taxonomy_results_by_level[[level]]


    log_taxonomy(
        level,
        "-level samples analyzed: ",
        nrow(
            result$counts
        )
    )


    log_taxonomy(
        level,
        "-level taxa detected: ",
        ncol(
            result$counts
        )
    )

}


log_taxonomy(
    "Taxonomic levels analyzed: ",
    paste(
        TAXONOMIC_LEVELS,
        collapse = ", "
    )
)


log_taxonomy(
    "Prevalence denominators are derived from Bracken sample counts."
)


log_taxonomy(
    "Results written to: ",
    TAXONOMY_ANALYSIS_DIR
)


log_taxonomy(
    "R objects written to: ",
    OBJECT_DIR
)


log_taxonomy(
    "Taxonomy analysis summary written to: ",
    taxonomy_summary_file
)


message(
    "============================================================"
)
